M48
; DRILL file {KiCad (6.0.5-0)} date 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-18T00:21:28+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0390
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0670
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1350
%
G90
G05
T1
X4.2305Y-3.3996
T2
X3.8085Y-3.565
X4.2415Y-3.565
T3
X3.815Y-3.11
X4.24Y-3.11
T4
X4.025Y-3.565
T0
M30
