M48
; DRILL file {KiCad (6.0.5-0)} date 
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2022-06-18T00:50:53+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.5-0)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0787
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1181
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T4C0.1575
%
G90
G05
T1
X3.8283Y-3.5894
X4.2283Y-3.5894
T2
X3.815Y-3.11
X4.24Y-3.11
T4
X4.0283Y-3.5894
T3
G00X4.0465Y-3.4394
M15
G01X4.0071Y-3.4394
M16
G05
T0
M30
